sudo: false
language: node_js
node_js:
  - "4.2" 
deploy:
  - provider: npm
    email: "reto.gmuer@zazuko.com"
    api_key:
      secure: "iR4chGmm/mtagWOmL/Ve1hh6TvHrHZ2kEiBImghdYjtj1VH6/zkBUsAH2HXZ8qDwQOk85yBeBcPBMvR+cVxQ4fhwihO4gyeh+DfbJW1Y5TwbgGbHCJ3a5vwTUILIp9y9zNYvOneEeVWV5hLR93KN6ZH8LRlEi1hCn41nUjAxnjWVsSKMu4m65OI6IEC3rLxqP//ioKoASDTkzA0f1wFF1Gek8kOcYGBM8ZszTrFvJ6WpXjNPsmRnHT5Q/NmP3Xdhze2IGb2Xv8w2GuCq3+CfKEVhm68HlJAfLVOgHzSgWqkY4aYSslck99C0JWLNsc2dYAgPBq4h6IYzb1wO/lBN6OSlJ4po0R7OG+RPNsjulLwdnZ+5UGjRb3aDe8LYkvBQbjBfem1lUmKXTt7FhvVHhn0OGrfWN19DxyVvCe4nqJsLA0D/pJTwwtZ3HNuB35dX1rZgkcbhyMpcTKT1TMsiplRHTCpBX2sC1wSAn3+8mq9ZsQMO7RpS45x17ehN4CmOgnr0nIJ9vfwHerIGcbOJpiuqWoRqQ0Dr4FhT/XKcfO0l/MBEwgnTapxZujTKxZ8lkxRCCxcFiixrOzC+YRJECCx5NAHW49qGqz3wec/A2V2XHPqf9tnzZQbNzkpyqdk3GfKJQ6pztM3erqWd+bCnPLHAtQpIl+vg8SMy+0k76ko="
    on:
      tags: true
  - provider: releases
    api_key:
      secure: "thFLk8ffrHxTx3xLucN2LmxWiOzRAqBExuATtt3Ycx2JoYM6XDCJuTA9qfru+loOTP7y/Om/EP/gV+InUtoSB/ic6kDnKe+LQ8OwD6fLcrnGlYqlyk0tNPLMPi5RA9nJKcnzushPU7zjs9SzB7jLQXVpAcOzELkrlU4B8nD/2PjBI+/ZaC+ifsUghrooXL2Qu6CvmYD3QazCcLiEx90lW6RGXGffyouOoHpRH3GhPg+y1zg/opkEsC1zOUJWlsK+wGYkW6CHjynDgJ9rPQo0hP1fVS/UaWxzajxebewf7Mb7Rctk3dEtvkwKKoNs8UKhOW3bMbniqckbnEQO52xts/mk36lwux7c1rhiqmD/A0HUHhMFU+nC3h6Ij9YzqIA1unQZrin8RFLDS9f8TZByVFtNA3NXuSYar/vaD5eHOZ4qQzAflIn6g1GZjS84IglfCqBcX9NUqpQBI4EmwAmGe0fLBeZnw3QdWyfJCTGDMGNnsF8Y4VUwXCMufDCJzdnquStnsChG5brNoy3V0CJYCnPAB4pCNrd63Hg79y2o6nAFKffvTlt1U4Gq0gHwo+DWPT4CjRqiUe9yi+fRJSJ41ZCigCdpLFuXUWWUn8K5hXwdcdKYROQmnSjL1dPZeKm/M+tBGrgwdYOvPhCWmfmEmoGelaF9Lgr9I4dHAk1wzH0="
    file: dist/rdf-store-ldp.js
    on:
      tags: true
#  - provider: bintray
#    file: ".bintray-descriptor.json"
#    user: "reto"
#    key:
#      secure: "HWpUoWFTGAjQoA/Lb0gbKSQHt59+Bfxoo0P80lEHlrJEqkwQ3uxo2pP9ERcUi1Qhw2jG0Hz/DIEsvCdRqclr/ZavXPIMy1LAe/ZMv1TiAKOwrfeREQGdXq3OmyfUf5fNV+ZQJXNjyY+8m64T4M3nJ3bDk/d9ro1uf5hd0UOyXrM5jc7HzsJT52u0eSwYjWMnYXTurHS6P/uhVl4ZYiujea4/37dq266VYq0h5et0Y5wvfBJ2NNqQCkBV/et8bRamHfEehbOoFG6UnnC/83fDbBxACYzHSXdEN3S8l1KSemUDadTs6QgvKmA4sipwS7DckZQ1XVB0UlXE4+NwP7uE2RwNvxlfP/HeVH3LdQcpAVojYXw0/Ffg6lvWOE+G0y0/peg/BEoNhtce4IhT11ZfenYETtnX0JKIkskB104KzLuBwtiivZsspbGWoDnCaNmJ69SzC9uy7420FuYvlexp1zNU0WGf2MVguJa/ZWss25nsJiEQzvPN6pkztvgZcw2P5K9lsRbokc02QHK7gAmBn+gYfvshdqOzADAvWJnXH/wdzHbHizvSXsYK2qYVRFUsVkkWtXUwcv1yE1hqxEHG0VWkim4bYMBf4LfMGyIUg1GeSUAqjMdPGbttgV790ExuTV2r6YW0HEwMn3oD1nLc2Y3FQ5b7PeOFdBKgGTE7WiU="
#    on:
#      tags: true